### ISSUE TITLE
Unittests and Python versions

### ISSUE THREAD

**Issue by olagrottvik** [olagrottvik/bust#31]
The software flow has at this moment no automated testing - this must be improved. Also, only one python version is used for manual testing - this must be improved!

**Comment by olagrottvik** [comment]
Too much effort is needed compared to utility

**Comment by maersdal** [comment]
（ノ゜Д゜）ノ︵┻━┻
confused.

**Comment by olagrottvik** [comment]
The issue was reopened to reflect that something is actually happening in this area
